apiVersion: v1
kind: Service
metadata:
  name: door-test-service # Replace with your info door-xxxx-servie
  namespace: production
spec:
  ports:
  - nodePort: 30011 # Set a port betwen 30000-32767.
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    k8s-app: door-test # Change to your item of your app door-xxxx.
  sessionAffinity: None
  type: NodePort
