kind: Deployment
apiVersion: apps/v1
metadata:
  name: door-test # Put your own value door-xxxx.
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: door-test # Put your own value door-xxxx.
  template:
    metadata:
      name: door-test # Put your own value door-xxxx.
      labels:
        k8s-app: door-test # Put your own value door-xxxx.
    spec:
      containers:
        - name: door-test # Put your own value door-xxxx.
          image: ccsadm/flask
          env:
          - name: FLASK_APP
            value: "/door/door-test.py # Put your own value /door/door-xxxx.py
